### ISSUE TITLE
Bridging calls

### ISSUE THREAD

**Issue by marc107** [mymindstorm/matrix-appservice-mumble#8]
Are there any chances getting mumble calls initiated through Matrix rooms?
Sound quality of mumble is quite better compared to matrix.
Thx!

**Comment by mymindstorm** [comment]
I'm not planning to build that functionality into this project. Someone suggested using https://github.com/Johni0702/mumble-web#matrix-widget to use mumble from Matrix rooms, hopefully that will work for you.
